name: Build and Deploy Script
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Adding Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build Angular App
        run: npm run build
      
      - name: Configure Git
        run: |
          git config --global user.email "DarioFT@users.noreply.github.com"
          git config --global user.name "DarioFT"
      
      - name: Deploy to gh pages
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx angular-cli-ghpages --dir=dist/depth-angular --base-href /depth-angular/
